
name: Docker Action
 
on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: | 
      docker build . --file Dockerfile --tag wbaa-papermill:$(date +%s)
      docker run wbaa-papermill:$(date +%s)
